import os
from pathlib import Path

# --- Configuration ---
PROJECT_ROOT = Path(__file__).parent.parent
WEEKLY_PREDICTIONS_DIR = PROJECT_ROOT / "data" / "pre_match"
COMBINED_RESULTS_FILE = PROJECT_ROOT / "data" / "combined_results.csv"

DATA_SOURCE = "csv"
DB_PARAMS = {
    "dbname": "football_db",
    "user": "user",
    "password": "password",
    "host": "localhost",
    "port": "5432",
}
TEXT_FILE_PATH = "Confidence-7.txt"
CSV_FILE_PATH = "dashboard/dashboard_data.csv"  # Path for saving/loading simulated CSV

# Map country names (as they appear in your data) to their flag codes
COUNTRY_CODE_MAP = {
    # media.api-sports.io
    "UEFA Champions League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/2.png",
    "UEFA Europa Conference League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/848.png",
    "UEFA Europa League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/3.png",
    "World": "https://fpp-dashboard-media.b-cdn.net/football/leagues/17.png",
    "Albania": "https://fpp-dashboard-media.b-cdn.net/flags/al.svg",
    "Algeria": "https://fpp-dashboard-media.b-cdn.net/flags/dz.svg",
    "Andorra": "https://fpp-dashboard-media.b-cdn.net/flags/ad.svg",
    "Angola": "https://fpp-dashboard-media.b-cdn.net/flags/ao.svg",
    "Antigua-And-Barbuda": "https://fpp-dashboard-media.b-cdn.net/flags/ag.svg",
    "Argentina": "https://fpp-dashboard-media.b-cdn.net/flags/ar.svg",
    "Armenia": "https://fpp-dashboard-media.b-cdn.net/flags/am.svg",
    "Aruba": "https://fpp-dashboard-media.b-cdn.net/flags/aw.svg",
    "Australia": "https://fpp-dashboard-media.b-cdn.net/flags/au.svg",
    "Austria": "https://fpp-dashboard-media.b-cdn.net/flags/at.svg",
    "Azerbaijan": "https://fpp-dashboard-media.b-cdn.net/flags/az.svg",
    "Bahrain": "https://fpp-dashboard-media.b-cdn.net/flags/bh.svg",
    "Bangladesh": "https://fpp-dashboard-media.b-cdn.net/flags/bd.svg",
    "Barbados": "https://fpp-dashboard-media.b-cdn.net/flags/bb.svg",
    "Belarus": "https://fpp-dashboard-media.b-cdn.net/flags/by.svg",
    "Belgium": "https://fpp-dashboard-media.b-cdn.net/flags/be.svg",
    "Belize": "https://fpp-dashboard-media.b-cdn.net/flags/bz.svg",
    "Benin": "https://fpp-dashboard-media.b-cdn.net/flags/bj.svg",
    "Bermuda": "https://fpp-dashboard-media.b-cdn.net/flags/bm.svg",
    "Bhutan": "https://fpp-dashboard-media.b-cdn.net/flags/bt.svg",
    "Bolivia": "https://fpp-dashboard-media.b-cdn.net/flags/bo.svg",
    "Bosnia": "https://fpp-dashboard-media.b-cdn.net/flags/ba.svg",
    "Botswana": "https://fpp-dashboard-media.b-cdn.net/flags/bw.svg",
    "Brazil": "https://fpp-dashboard-media.b-cdn.net/flags/br.svg",
    "Bulgaria": "https://fpp-dashboard-media.b-cdn.net/flags/bg.svg",
    "Burkina-Faso": "https://fpp-dashboard-media.b-cdn.net/flags/bf.svg",
    "Burundi": "https://fpp-dashboard-media.b-cdn.net/flags/bi.svg",
    "Cambodia": "https://fpp-dashboard-media.b-cdn.net/flags/kh.svg",
    "Cameroon": "https://fpp-dashboard-media.b-cdn.net/flags/cm.svg",
    "Canada": "https://fpp-dashboard-media.b-cdn.net/flags/ca.svg",
    "Chile": "https://fpp-dashboard-media.b-cdn.net/flags/cl.svg",
    "China": "https://fpp-dashboard-media.b-cdn.net/flags/cn.svg",
    "Chinese-Taipei": "https://fpp-dashboard-media.b-cdn.net/flags/tw.svg",
    "Colombia": "https://fpp-dashboard-media.b-cdn.net/flags/co.svg",
    "Congo": "https://fpp-dashboard-media.b-cdn.net/flags/cd.svg",
    "Congo-DR": "https://fpp-dashboard-media.b-cdn.net/flags/cg.svg",
    "Costa-Rica": "https://fpp-dashboard-media.b-cdn.net/flags/cr.svg",
    "Crimea": "https://fpp-dashboard-media.b-cdn.net/flags/ua.svg",
    "Croatia": "https://fpp-dashboard-media.b-cdn.net/flags/hr.svg",
    "Cuba": "https://fpp-dashboard-media.b-cdn.net/flags/cu.svg",
    "Curacao": "https://fpp-dashboard-media.b-cdn.net/flags/cw.svg",
    "Cyprus": "https://fpp-dashboard-media.b-cdn.net/flags/cy.svg",
    "Czech-Republic": "https://fpp-dashboard-media.b-cdn.net/flags/cz.svg",
    "Denmark": "https://fpp-dashboard-media.b-cdn.net/flags/dk.svg",
    "Dominican-Republic": "https://fpp-dashboard-media.b-cdn.net/flags/do.svg",
    "Ecuador": "https://fpp-dashboard-media.b-cdn.net/flags/ec.svg",
    "Egypt": "https://fpp-dashboard-media.b-cdn.net/flags/eg.svg",
    "El-Salvador": "https://fpp-dashboard-media.b-cdn.net/flags/sv.svg",
    "England": "https://fpp-dashboard-media.b-cdn.net/flags/gb-eng.svg",
    "Estonia": "https://fpp-dashboard-media.b-cdn.net/flags/ee.svg",
    "Eswatini": "https://fpp-dashboard-media.b-cdn.net/flags/sz.svg",
    "Ethiopia": "https://fpp-dashboard-media.b-cdn.net/flags/et.svg",
    "Faroe-Islands": "https://fpp-dashboard-media.b-cdn.net/flags/fo.svg",
    "Fiji": "https://fpp-dashboard-media.b-cdn.net/flags/fj.svg",
    "Finland": "https://fpp-dashboard-media.b-cdn.net/flags/fi.svg",
    "France": "https://fpp-dashboard-media.b-cdn.net/flags/fr.svg",
    "Gabon": "https://fpp-dashboard-media.b-cdn.net/flags/ga.svg",
    "Gambia": "https://fpp-dashboard-media.b-cdn.net/flags/gm.svg",
    "Georgia": "https://fpp-dashboard-media.b-cdn.net/flags/ge.svg",
    "Germany": "https://fpp-dashboard-media.b-cdn.net/flags/de.svg",
    "Ghana": "https://fpp-dashboard-media.b-cdn.net/flags/gh.svg",
    "Gibraltar": "https://fpp-dashboard-media.b-cdn.net/flags/gi.svg",
    "Greece": "https://fpp-dashboard-media.b-cdn.net/flags/gr.svg",
    "Grenada": "https://fpp-dashboard-media.b-cdn.net/flags/gd.svg",
    "Guadeloupe": "https://fpp-dashboard-media.b-cdn.net/flags/gp.svg",
    "Guatemala": "https://fpp-dashboard-media.b-cdn.net/flags/gt.svg",
    "Guinea": "https://fpp-dashboard-media.b-cdn.net/flags/gn.svg",
    "Haiti": "https://fpp-dashboard-media.b-cdn.net/flags/ht.svg",
    "Honduras": "https://fpp-dashboard-media.b-cdn.net/flags/hn.svg",
    "Hong-Kong": "https://fpp-dashboard-media.b-cdn.net/flags/hk.svg",
    "Hungary": "https://fpp-dashboard-media.b-cdn.net/flags/hu.svg",
    "Iceland": "https://fpp-dashboard-media.b-cdn.net/flags/is.svg",
    "India": "https://fpp-dashboard-media.b-cdn.net/flags/in.svg",
    "Indonesia": "https://fpp-dashboard-media.b-cdn.net/flags/id.svg",
    "Iran": "https://fpp-dashboard-media.b-cdn.net/flags/ir.svg",
    "Iraq": "https://fpp-dashboard-media.b-cdn.net/flags/iq.svg",
    "Ireland": "https://fpp-dashboard-media.b-cdn.net/flags/ie.svg",
    "Israel": "https://fpp-dashboard-media.b-cdn.net/flags/il.svg",
    "Italy": "https://fpp-dashboard-media.b-cdn.net/flags/it.svg",
    "Ivory-Coast": "https://fpp-dashboard-media.b-cdn.net/flags/ci.svg",
    "Jamaica": "https://fpp-dashboard-media.b-cdn.net/flags/jm.svg",
    "Japan": "https://fpp-dashboard-media.b-cdn.net/flags/jp.svg",
    "Jordan": "https://fpp-dashboard-media.b-cdn.net/flags/jo.svg",
    "Kazakhstan": "https://fpp-dashboard-media.b-cdn.net/flags/kz.svg",
    "Kenya": "https://fpp-dashboard-media.b-cdn.net/flags/ke.svg",
    "Kosovo": "https://fpp-dashboard-media.b-cdn.net/flags/xk.svg",
    "Kuwait": "https://fpp-dashboard-media.b-cdn.net/flags/kw.svg",
    "Kyrgyzstan": "https://fpp-dashboard-media.b-cdn.net/flags/kg.svg",
    "Laos": "https://fpp-dashboard-media.b-cdn.net/flags/la.svg",
    "Latvia": "https://fpp-dashboard-media.b-cdn.net/flags/lv.svg",
    "Lebanon": "https://fpp-dashboard-media.b-cdn.net/flags/lb.svg",
    "Lesotho": "https://fpp-dashboard-media.b-cdn.net/flags/ls.svg",
    "Liberia": "https://fpp-dashboard-media.b-cdn.net/flags/lr.svg",
    "Libya": "https://fpp-dashboard-media.b-cdn.net/flags/ly.svg",
    "Liechtenstein": "https://fpp-dashboard-media.b-cdn.net/flags/li.svg",
    "Lithuania": "https://fpp-dashboard-media.b-cdn.net/flags/lt.svg",
    "Luxembourg": "https://fpp-dashboard-media.b-cdn.net/flags/lu.svg",
    "Macao": "https://fpp-dashboard-media.b-cdn.net/flags/mo.svg",
    "Macedonia": "https://fpp-dashboard-media.b-cdn.net/flags/mk.svg",
    "Malawi": "https://fpp-dashboard-media.b-cdn.net/flags/mw.svg",
    "Malaysia": "https://fpp-dashboard-media.b-cdn.net/flags/my.svg",
    "Maldives": "https://fpp-dashboard-media.b-cdn.net/flags/mv.svg",
    "Mali": "https://fpp-dashboard-media.b-cdn.net/flags/ml.svg",
    "Malta": "https://fpp-dashboard-media.b-cdn.net/flags/mt.svg",
    "Mauritania": "https://fpp-dashboard-media.b-cdn.net/flags/mr.svg",
    "Mauritius": "https://fpp-dashboard-media.b-cdn.net/flags/mu.svg",
    "Mexico": "https://fpp-dashboard-media.b-cdn.net/flags/mx.svg",
    "Moldova": "https://fpp-dashboard-media.b-cdn.net/flags/md.svg",
    "Mongolia": "https://fpp-dashboard-media.b-cdn.net/flags/mn.svg",
    "Montenegro": "https://fpp-dashboard-media.b-cdn.net/flags/me.svg",
    "Morocco": "https://fpp-dashboard-media.b-cdn.net/flags/ma.svg",
    "Myanmar": "https://fpp-dashboard-media.b-cdn.net/flags/mm.svg",
    "Namibia": "https://fpp-dashboard-media.b-cdn.net/flags/na.svg",
    "Nepal": "https://fpp-dashboard-media.b-cdn.net/flags/np.svg",
    "Netherlands": "https://fpp-dashboard-media.b-cdn.net/flags/nl.svg",
    "New-Zealand": "https://fpp-dashboard-media.b-cdn.net/flags/nz.svg",
    "Nicaragua": "https://fpp-dashboard-media.b-cdn.net/flags/ni.svg",
    "Nigeria": "https://fpp-dashboard-media.b-cdn.net/flags/ng.svg",
    "Northern-Ireland": "https://fpp-dashboard-media.b-cdn.net/flags/gb-nir.svg",
    "Norway": "https://fpp-dashboard-media.b-cdn.net/flags/no.svg",
    "Oman": "https://fpp-dashboard-media.b-cdn.net/flags/om.svg",
    "Pakistan": "https://fpp-dashboard-media.b-cdn.net/flags/pk.svg",
    "Palestine": "https://fpp-dashboard-media.b-cdn.net/flags/ps.svg",
    "Panama": "https://fpp-dashboard-media.b-cdn.net/flags/pa.svg",
    "Paraguay": "https://fpp-dashboard-media.b-cdn.net/flags/py.svg",
    "Peru": "https://fpp-dashboard-media.b-cdn.net/flags/pe.svg",
    "Philippines": "https://fpp-dashboard-media.b-cdn.net/flags/ph.svg",
    "Poland": "https://fpp-dashboard-media.b-cdn.net/flags/pl.svg",
    "Portugal": "https://fpp-dashboard-media.b-cdn.net/flags/pt.svg",
    "Qatar": "https://fpp-dashboard-media.b-cdn.net/flags/qa.svg",
    "Romania": "https://fpp-dashboard-media.b-cdn.net/flags/ro.svg",
    "Russia": "https://fpp-dashboard-media.b-cdn.net/flags/ru.svg",
    "Rwanda": "https://fpp-dashboard-media.b-cdn.net/flags/rw.svg",
    "San-Marino": "https://fpp-dashboard-media.b-cdn.net/flags/sm.svg",
    "Saudi-Arabia": "https://fpp-dashboard-media.b-cdn.net/flags/sa.svg",
    "Scotland": "https://fpp-dashboard-media.b-cdn.net/flags/gb-sct.svg",
    "Senegal": "https://fpp-dashboard-media.b-cdn.net/flags/sn.svg",
    "Serbia": "https://fpp-dashboard-media.b-cdn.net/flags/rs.svg",
    "Singapore": "https://fpp-dashboard-media.b-cdn.net/flags/sg.svg",
    "Slovakia": "https://fpp-dashboard-media.b-cdn.net/flags/sk.svg",
    "Slovenia": "https://fpp-dashboard-media.b-cdn.net/flags/si.svg",
    "Somalia": "https://fpp-dashboard-media.b-cdn.net/flags/so.svg",
    "South-Africa": "https://fpp-dashboard-media.b-cdn.net/flags/za.svg",
    "South-Korea": "https://fpp-dashboard-media.b-cdn.net/flags/kr.svg",
    "Spain": "https://fpp-dashboard-media.b-cdn.net/flags/es.svg",
    "Sudan": "https://fpp-dashboard-media.b-cdn.net/flags/sd.svg",
    "Suriname": "https://fpp-dashboard-media.b-cdn.net/flags/sr.svg",
    "Sweden": "https://fpp-dashboard-media.b-cdn.net/flags/se.svg",
    "Switzerland": "https://fpp-dashboard-media.b-cdn.net/flags/ch.svg",
    "Syria": "https://fpp-dashboard-media.b-cdn.net/flags/sy.svg",
    "Tajikistan": "https://fpp-dashboard-media.b-cdn.net/flags/tj.svg",
    "Tanzania": "https://fpp-dashboard-media.b-cdn.net/flags/tz.svg",
    "Thailand": "https://fpp-dashboard-media.b-cdn.net/flags/th.svg",
    "Togo": "https://fpp-dashboard-media.b-cdn.net/flags/tg.svg",
    "Trinidad-And-Tobago": "https://fpp-dashboard-media.b-cdn.net/flags/tt.svg",
    "Tunisia": "https://fpp-dashboard-media.b-cdn.net/flags/tn.svg",
    "Turkey": "https://fpp-dashboard-media.b-cdn.net/flags/tr.svg",
    "Turkmenistan": "https://fpp-dashboard-media.b-cdn.net/flags/tm.svg",
    "Uganda": "https://fpp-dashboard-media.b-cdn.net/flags/ug.svg",
    "Ukraine": "https://fpp-dashboard-media.b-cdn.net/flags/ua.svg",
    "United-Arab-Emirates": "https://fpp-dashboard-media.b-cdn.net/flags/ae.svg",
    "Uruguay": "https://fpp-dashboard-media.b-cdn.net/flags/uy.svg",
    "USA": "https://fpp-dashboard-media.b-cdn.net/flags/us.svg",
    "Uzbekistan": "https://fpp-dashboard-media.b-cdn.net/flags/uz.svg",
    "Venezuela": "https://fpp-dashboard-media.b-cdn.net/flags/ve.svg",
    "Vietnam": "https://fpp-dashboard-media.b-cdn.net/flags/vn.svg",
    "Wales": "https://fpp-dashboard-media.b-cdn.net/flags/gb-wls.svg",
    "Yemen": "https://fpp-dashboard-media.b-cdn.net/flags/ye.svg",
    "Zambia": "https://fpp-dashboard-media.b-cdn.net/flags/zm.svg",
    "Zimbabwe": "https://fpp-dashboard-media.b-cdn.net/flags/zw.svg",
}

LEAGUE_CODE_MAP = {  # media.api-sports.io
    "World, AFC Champions League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/17.png",
    "World, UEFA Champions League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/2.png",
    "World, UEFA Europa Conference League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/848.png",
    "World, UEFA Europa League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/3.png",
    "Algeria, Ligue 1": "https://fpp-dashboard-media.b-cdn.net/football/leagues/186.png",
    "Egypt, Premier League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/233.png",
    "South-Africa, Premier Soccer League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/288.png",
    "Tanzania, Ligi kuu Bara": "https://fpp-dashboard-media.b-cdn.net/football/leagues/567.png",
    "Australia, A-League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/188.png",
    "China, Super League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/169.png",
    "China, League One": "https://fpp-dashboard-media.b-cdn.net/football/leagues/170.png",
    "India, Indian Super League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/323.png",
    "Indonesia, Liga 1": "https://fpp-dashboard-media.b-cdn.net/football/leagues/274.png",
    "Iran, Persian Gulf Pro League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/290.png",
    "Japan, J1 League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/98.png",
    "Japan, J2 League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/99.png",
    "Malaysia, Super League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/278.png",
    "Saudi-Arabia, Pro League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/307.png",
    "Singapore, Premier League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/368.png",
    "South-Korea, K League 1": "https://fpp-dashboard-media.b-cdn.net/football/leagues/292.png",
    "South-Korea, K League 2": "https://fpp-dashboard-media.b-cdn.net/football/leagues/293.png",
    "Vietnam, V.League 1": "https://fpp-dashboard-media.b-cdn.net/football/leagues/340.png",
    "Austria, Bundesliga": "https://fpp-dashboard-media.b-cdn.net/football/leagues/218.png",
    "Austria, 2. Liga": "https://fpp-dashboard-media.b-cdn.net/football/leagues/219.png",
    "Azerbaijan, Premyer Liqa": "https://fpp-dashboard-media.b-cdn.net/football/leagues/419.png",
    "Belarus, Premier League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/116.png",
    "Belgium, Jupiler Pro League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/144.png",
    "Croatia, HNL": "https://fpp-dashboard-media.b-cdn.net/football/leagues/210.png",
    "Czech-Republic, Czech Liga": "https://fpp-dashboard-media.b-cdn.net/football/leagues/345.png",
    "Denmark, Superliga": "https://fpp-dashboard-media.b-cdn.net/football/leagues/119.png",
    "England, Premier League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/39.png",
    "England, Championship": "https://fpp-dashboard-media.b-cdn.net/football/leagues/40.png",
    "England, League One": "https://fpp-dashboard-media.b-cdn.net/football/leagues/41.png",
    "England, League Two": "https://fpp-dashboard-media.b-cdn.net/football/leagues/42.png",
    "Faroe-Islands, Meistaradeildin": "https://fpp-dashboard-media.b-cdn.net/football/leagues/367.png",
    "Finland, Veikkausliiga": "https://fpp-dashboard-media.b-cdn.net/football/leagues/244.png",
    "France, Ligue 1": "https://fpp-dashboard-media.b-cdn.net/football/leagues/61.png",
    "France, Ligue 2": "https://fpp-dashboard-media.b-cdn.net/football/leagues/62.png",
    "Germany, Bundesliga": "https://fpp-dashboard-media.b-cdn.net/football/leagues/78.png",
    "Germany, 2. Bundesliga": "https://fpp-dashboard-media.b-cdn.net/football/leagues/79.png",
    "Iceland, Úrvalsdeild": "https://fpp-dashboard-media.b-cdn.net/football/leagues/164.png",
    "Iceland, 1. Deild": "https://fpp-dashboard-media.b-cdn.net/football/leagues/165.png",
    "Italy, Serie A": "https://fpp-dashboard-media.b-cdn.net/football/leagues/135.png",
    "Italy, Serie B": "https://fpp-dashboard-media.b-cdn.net/football/leagues/136.png",
    "Ireland, Premier Division": "https://fpp-dashboard-media.b-cdn.net/football/leagues/357.png",
    "Ireland, First Division": "https://fpp-dashboard-media.b-cdn.net/football/leagues/358.png",
    "Latvia, Virsliga": "https://fpp-dashboard-media.b-cdn.net/football/leagues/365.png",
    "Latvia, 1. Liga": "https://fpp-dashboard-media.b-cdn.net/football/leagues/364.png",
    "Lithuania, A Lyga": "https://fpp-dashboard-media.b-cdn.net/football/leagues/362.png",
    "Netherlands, Eredivisie": "https://fpp-dashboard-media.b-cdn.net/football/leagues/88.png",
    "Netherlands, Eerste Divisie": "https://fpp-dashboard-media.b-cdn.net/football/leagues/89.png",
    "Norway, Eliteserien": "https://fpp-dashboard-media.b-cdn.net/football/leagues/103.png",
    "Norway, 1. Division": "https://fpp-dashboard-media.b-cdn.net/football/leagues/104.png",
    "Portugal, Primeira Liga": "https://fpp-dashboard-media.b-cdn.net/football/leagues/94.png",
    "Poland, Ekstraklasa": "https://fpp-dashboard-media.b-cdn.net/football/leagues/106.png",
    "Russia, Premier League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/235.png",
    "Scotland, Premiership": "https://fpp-dashboard-media.b-cdn.net/football/leagues/179.png",
    "Spain, La Liga": "https://fpp-dashboard-media.b-cdn.net/football/leagues/140.png",
    "Spain, Segunda División": "https://fpp-dashboard-media.b-cdn.net/football/leagues/141.png",
    "Sweden, Allsvenskan": "https://fpp-dashboard-media.b-cdn.net/football/leagues/113.png",
    "Sweden, Superettan": "https://fpp-dashboard-media.b-cdn.net/football/leagues/114.png",
    "Switzerland, Super League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/207.png",
    "Turkey, Süper Lig": "https://fpp-dashboard-media.b-cdn.net/football/leagues/203.png",
    "Turkey, 1. Lig": "https://fpp-dashboard-media.b-cdn.net/football/leagues/204.png",
    "Ukraine, Premier League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/333.png",
    "Wales, Premier League": "https://fpp-dashboard-media.b-cdn.net/football/leagues/110.png",
    "Argentina, Liga Profesional Argentina": "https://fpp-dashboard-media.b-cdn.net/football/leagues/128.png",
    "Argentina, Primera B Metropolitana": "https://fpp-dashboard-media.b-cdn.net/football/leagues/131.png",
    "Brazil, Serie A": "https://fpp-dashboard-media.b-cdn.net/football/leagues/71.png",
    "Brazil, Serie B": "https://fpp-dashboard-media.b-cdn.net/football/leagues/72.png",
    "Chile, Primera División": "https://fpp-dashboard-media.b-cdn.net/football/leagues/265.png",
    "Colombia, Primera A": "https://fpp-dashboard-media.b-cdn.net/football/leagues/239.png",
    "Colombia, Primera B": "https://fpp-dashboard-media.b-cdn.net/football/leagues/240.png",
    "Costa-Rica, Primera División": "https://fpp-dashboard-media.b-cdn.net/football/leagues/162.png",
    "Ecuador, Liga Pro": "https://fpp-dashboard-media.b-cdn.net/football/leagues/242.png",
    "Mexico, Liga MX": "https://fpp-dashboard-media.b-cdn.net/football/leagues/262.png",
    "Uruguay, Primera División - Apertura": "https://fpp-dashboard-media.b-cdn.net/football/leagues/268.png",
    "USA, Major League Soccer": "https://fpp-dashboard-media.b-cdn.net/football/leagues/253.png",
}
# Base URL for the flags
FLAG_BASE_URL = "https://fpp-dashboard-media.b-cdn.net/flags/"  # media.api-sports.io

MESSAGE_TIMEOUT_SECONDS = 7  # How long messages should persist (in seconds)

# --- Define Default Values for New Filters (use these in reset) ---
DEFAULT_TIME_RANGE = (0, 23)
DEFAULT_RANK_RANGE = (1, 50)  # A sensible wide default for ranks
DEFAULT_ODDS_RANGE = (1.01, 25.0)  # A sensible wide default for odds

# --- Define colors ---
GREEN: str = "#57D58D"  # "#A1FF0A"  # "#A5BE00"  # "#A7C957"
